INSERT INTO TB_COD_OCORRENCIAS_TIVIT (cod,desc_ocorrencias) VALUES ('0'	,'Processo de Transporte já Iniciado');
INSERT INTO TB_COD_OCORRENCIAS_TIVIT (cod,desc_ocorrencias) VALUES ('1'	,'Entrega Realizada Normalmente');
INSERT INTO TB_COD_OCORRENCIAS_TIVIT (cod,desc_ocorrencias) VALUES ('2'	,'Entrega Fora da Data Programada');
INSERT INTO TB_COD_OCORRENCIAS_TIVIT (cod,desc_ocorrencias) VALUES ('3'	,'Recusa por Falta de Pedido de Compra');
INSERT INTO TB_COD_OCORRENCIAS_TIVIT (cod,desc_ocorrencias) VALUES ('4'	,'Recusa por Pedido de Compra Cancelado');
INSERT INTO TB_COD_OCORRENCIAS_TIVIT (cod,desc_ocorrencias) VALUES ('5'	,'Falta de Espaço Físico no Depósito do Cliente Destino');
INSERT INTO TB_COD_OCORRENCIAS_TIVIT (cod,desc_ocorrencias) VALUES ('6'	,'Endereço do Cliente Destino não Localizado');
INSERT INTO TB_COD_OCORRENCIAS_TIVIT (cod,desc_ocorrencias) VALUES ('7'	,'Devolução não Autorizada pelo Cliente');
INSERT INTO TB_COD_OCORRENCIAS_TIVIT (cod,desc_ocorrencias) VALUES ('8'	,'Preço Mercadoria em Desacordo com o Pedido Compra');
INSERT INTO TB_COD_OCORRENCIAS_TIVIT (cod,desc_ocorrencias) VALUES ('09'	,'Mercadoria em Desacordo com o Pedido Compra');
INSERT INTO TB_COD_OCORRENCIAS_TIVIT (cod,desc_ocorrencias) VALUES ('10'	,'Cliente Destino somente Recebe Mercadoria com Frete Pago');
INSERT INTO TB_COD_OCORRENCIAS_TIVIT (cod,desc_ocorrencias) VALUES ('11'	,'Recusa por Deficiência Embalagem Mercadoria');
INSERT INTO TB_COD_OCORRENCIAS_TIVIT (cod,desc_ocorrencias) VALUES ('12'	,'Redespacho não Indicado');
INSERT INTO TB_COD_OCORRENCIAS_TIVIT (cod,desc_ocorrencias) VALUES ('13'	,'Transportadora não Atende a Cidade do Cliente Destino');
INSERT INTO TB_COD_OCORRENCIAS_TIVIT (cod,desc_ocorrencias) VALUES ('14'	,'Mercadoria Sinistrada');
INSERT INTO TB_COD_OCORRENCIAS_TIVIT (cod,desc_ocorrencias) VALUES ('15'	,'Embalagem Sinistrada');
INSERT INTO TB_COD_OCORRENCIAS_TIVIT (cod,desc_ocorrencias) VALUES ('16'	,'Pedido de Compras em Duplicidade');
INSERT INTO TB_COD_OCORRENCIAS_TIVIT (cod,desc_ocorrencias) VALUES ('17'	,'Mercadoria fora da Embalagem de Atacadista');
INSERT INTO TB_COD_OCORRENCIAS_TIVIT (cod,desc_ocorrencias) VALUES ('18'	,'Mercadorias Trocadas');
INSERT INTO TB_COD_OCORRENCIAS_TIVIT (cod,desc_ocorrencias) VALUES ('19'	,'Reentrega Solicitada pelo Cliente');
INSERT INTO TB_COD_OCORRENCIAS_TIVIT (cod,desc_ocorrencias) VALUES ('20'	,'Entrega Prejudicada por Horário/Falta de Tempo Hábil');
INSERT INTO TB_COD_OCORRENCIAS_TIVIT (cod,desc_ocorrencias) VALUES ('21'	,'Estabelecimento Fechado');
INSERT INTO TB_COD_OCORRENCIAS_TIVIT (cod,desc_ocorrencias) VALUES ('22'	,'Reentrega sem Cobrança do Cliente');
INSERT INTO TB_COD_OCORRENCIAS_TIVIT (cod,desc_ocorrencias) VALUES ('23'	,'Extravio de Mercadoria em Trânsito');
INSERT INTO TB_COD_OCORRENCIAS_TIVIT (cod,desc_ocorrencias) VALUES ('24'	,'Mercadoria Reentregue ao Cliente Destino');
INSERT INTO TB_COD_OCORRENCIAS_TIVIT (cod,desc_ocorrencias) VALUES ('25'	,'Mercadoria Devolvida ao Cliente de Origem');
INSERT INTO TB_COD_OCORRENCIAS_TIVIT (cod,desc_ocorrencias) VALUES ('26'	,'Nota Fiscal Retida pela Fiscalização');
INSERT INTO TB_COD_OCORRENCIAS_TIVIT (cod,desc_ocorrencias) VALUES ('27'	,'Roubo de Carga');
INSERT INTO TB_COD_OCORRENCIAS_TIVIT (cod,desc_ocorrencias) VALUES ('28'	,'Mercadoria Retida até Segunda Ordem');
INSERT INTO TB_COD_OCORRENCIAS_TIVIT (cod,desc_ocorrencias) VALUES ('29'	,'Cliente Retira Mercadoria na Transportadora');
INSERT INTO TB_COD_OCORRENCIAS_TIVIT (cod,desc_ocorrencias) VALUES ('30'	,'Problema com a Documentação (Nota fiscal e/ou CTRC)');
INSERT INTO TB_COD_OCORRENCIAS_TIVIT (cod,desc_ocorrencias) VALUES ('31'	,'Entrega com Indenização Efetuada');
INSERT INTO TB_COD_OCORRENCIAS_TIVIT (cod,desc_ocorrencias) VALUES ('32'	,'Falta com Solicitação de Reposição');
INSERT INTO TB_COD_OCORRENCIAS_TIVIT (cod,desc_ocorrencias) VALUES ('33'	,'Falta com Busca/Reconferência');
INSERT INTO TB_COD_OCORRENCIAS_TIVIT (cod,desc_ocorrencias) VALUES ('34'	,'Cliente Fechado para Balanço');
INSERT INTO TB_COD_OCORRENCIAS_TIVIT (cod,desc_ocorrencias) VALUES ('35'	,'Quantidade de Produto em Desacordo (Nota fiscal e/ou Pedido)');
INSERT INTO TB_COD_OCORRENCIAS_TIVIT (cod,desc_ocorrencias) VALUES ('36'	,'Extravio de documentos pela cia. Aérea                                         - Cód. Transp. Aéreo');
INSERT INTO TB_COD_OCORRENCIAS_TIVIT (cod,desc_ocorrencias) VALUES ('37'	,'Extravio de carga pela cia. Aérea                                                   -Cód. Transp. Aéreo');
INSERT INTO TB_COD_OCORRENCIAS_TIVIT (cod,desc_ocorrencias) VALUES ('38'	,'Avaria de carga pela cia. Aérea                                                      -Cód. Transp. Aéreo');
INSERT INTO TB_COD_OCORRENCIAS_TIVIT (cod,desc_ocorrencias) VALUES ('39'	,'Corte de carga na pista                                                                 -Cód. Transp. Aéreo');
INSERT INTO TB_COD_OCORRENCIAS_TIVIT (cod,desc_ocorrencias) VALUES ('40'	,'Aeroporto fechado na origem                                                          -Cód. Transp. Aéreo');
INSERT INTO TB_COD_OCORRENCIAS_TIVIT (cod,desc_ocorrencias) VALUES ('41'	,'Pedido de Compra Incompleto');
INSERT INTO TB_COD_OCORRENCIAS_TIVIT (cod,desc_ocorrencias) VALUES ('42'	,'Nota fiscal com Produtos de Setores Diferentes');
INSERT INTO TB_COD_OCORRENCIAS_TIVIT (cod,desc_ocorrencias) VALUES ('43'	,'Feriado Local/Nacional');
INSERT INTO TB_COD_OCORRENCIAS_TIVIT (cod,desc_ocorrencias) VALUES ('44'	,'Excesso de Veículos');
INSERT INTO TB_COD_OCORRENCIAS_TIVIT (cod,desc_ocorrencias) VALUES ('45'	,'Cliente Destino Encerrou Atividades');
INSERT INTO TB_COD_OCORRENCIAS_TIVIT (cod,desc_ocorrencias) VALUES ('46'	,'Responsável de Recebimento Ausente');
INSERT INTO TB_COD_OCORRENCIAS_TIVIT (cod,desc_ocorrencias) VALUES ('47'	,'Cliente Destino em Greve');
INSERT INTO TB_COD_OCORRENCIAS_TIVIT (cod,desc_ocorrencias) VALUES ('48'	,' Aeroporto fechado no destino                                                        -Cód. Transp. Aéreo');
INSERT INTO TB_COD_OCORRENCIAS_TIVIT (cod,desc_ocorrencias) VALUES ('49'	,' Vôo cancelado                                                                             -Cód. Transp. Aéreo');
INSERT INTO TB_COD_OCORRENCIAS_TIVIT (cod,desc_ocorrencias) VALUES ('50'	,'Greve nacional (Greve Geral)');
INSERT INTO TB_COD_OCORRENCIAS_TIVIT (cod,desc_ocorrencias) VALUES ('51'	,'Mercadoria Vencida (Data de Validade Expirada)');
INSERT INTO TB_COD_OCORRENCIAS_TIVIT (cod,desc_ocorrencias) VALUES ('52'	,'Mercadoria Redespachada (Entregue para Redespacho)');
INSERT INTO TB_COD_OCORRENCIAS_TIVIT (cod,desc_ocorrencias) VALUES ('53'	,'Mercadoria não foi Embarcada, Permanecendo na Origem');
INSERT INTO TB_COD_OCORRENCIAS_TIVIT (cod,desc_ocorrencias) VALUES ('54'	,'Mercadoria Embarcada sem Conhecimento/Conhecimento não Embarcado');
INSERT INTO TB_COD_OCORRENCIAS_TIVIT (cod,desc_ocorrencias) VALUES ('55'	,'Endereço de Transportadora de Redespacho não Localizado/Informado');
INSERT INTO TB_COD_OCORRENCIAS_TIVIT (cod,desc_ocorrencias) VALUES ('56'	,'Cliente não Aceita Mercadoria com Pagamento de Reembolso');
INSERT INTO TB_COD_OCORRENCIAS_TIVIT (cod,desc_ocorrencias) VALUES ('57'	,'Transportadora não Atende a Cidade da Transportadora de Redespacho');
INSERT INTO TB_COD_OCORRENCIAS_TIVIT (cod,desc_ocorrencias) VALUES ('58'	,'Quebra do Veiculo de Entrega');
INSERT INTO TB_COD_OCORRENCIAS_TIVIT (cod,desc_ocorrencias) VALUES ('59'	,'Cliente sem Verba para Pagar o Frete');
INSERT INTO TB_COD_OCORRENCIAS_TIVIT (cod,desc_ocorrencias) VALUES ('60'	,'Endereço de Entrega Errado');
INSERT INTO TB_COD_OCORRENCIAS_TIVIT (cod,desc_ocorrencias) VALUES ('61'	,'Cliente sem Verba para Reembolso');
INSERT INTO TB_COD_OCORRENCIAS_TIVIT (cod,desc_ocorrencias) VALUES ('62'	,'Recusa da Carga por Valor de Frete Errado');
INSERT INTO TB_COD_OCORRENCIAS_TIVIT (cod,desc_ocorrencias) VALUES ('63'	,'Identificação do Cliente não Informada/Enviada/Insuficiente');
INSERT INTO TB_COD_OCORRENCIAS_TIVIT (cod,desc_ocorrencias) VALUES ('64'	,'Cliente não Identificado/Cadastrado');
INSERT INTO TB_COD_OCORRENCIAS_TIVIT (cod,desc_ocorrencias) VALUES ('65'	,'Entrar em Contato com o Comprador');
INSERT INTO TB_COD_OCORRENCIAS_TIVIT (cod,desc_ocorrencias) VALUES ('66'	,'Troca não Disponível');
INSERT INTO TB_COD_OCORRENCIAS_TIVIT (cod,desc_ocorrencias) VALUES ('67'	,'Fins Estatísticos');
INSERT INTO TB_COD_OCORRENCIAS_TIVIT (cod,desc_ocorrencias) VALUES ('68'	,'Data de Entrega Diferente do Pedido');
INSERT INTO TB_COD_OCORRENCIAS_TIVIT (cod,desc_ocorrencias) VALUES ('69'	,'Substituição Tributária');
INSERT INTO TB_COD_OCORRENCIAS_TIVIT (cod,desc_ocorrencias) VALUES ('70'	,'Sistema Fora do Ar');
INSERT INTO TB_COD_OCORRENCIAS_TIVIT (cod,desc_ocorrencias) VALUES ('71'	,'Cliente Destino não Recebe Pedido Parcial');
INSERT INTO TB_COD_OCORRENCIAS_TIVIT (cod,desc_ocorrencias) VALUES ('72'	,'Cliente Destino só Recebe Pedido Parcial');
INSERT INTO TB_COD_OCORRENCIAS_TIVIT (cod,desc_ocorrencias) VALUES ('73'	,'Redespacho somente com Frete Pago');
INSERT INTO TB_COD_OCORRENCIAS_TIVIT (cod,desc_ocorrencias) VALUES ('74'	,'Funcionário não autorizado a Receber Mercadorias');
INSERT INTO TB_COD_OCORRENCIAS_TIVIT (cod,desc_ocorrencias) VALUES ('75'	,'Mercadoria Embarcada para Rota Indevida');
INSERT INTO TB_COD_OCORRENCIAS_TIVIT (cod,desc_ocorrencias) VALUES ('76'	,'Estrada/Entrada de Acesso Interditada');
INSERT INTO TB_COD_OCORRENCIAS_TIVIT (cod,desc_ocorrencias) VALUES ('77'	,'Cliente Destino Mudou de Endereço');
INSERT INTO TB_COD_OCORRENCIAS_TIVIT (cod,desc_ocorrencias) VALUES ('78'	,'Avaria Total');
INSERT INTO TB_COD_OCORRENCIAS_TIVIT (cod,desc_ocorrencias) VALUES ('79'	,'Avaria Parcial.');
INSERT INTO TB_COD_OCORRENCIAS_TIVIT (cod,desc_ocorrencias) VALUES ('80'	,'Extravio Total');
INSERT INTO TB_COD_OCORRENCIAS_TIVIT (cod,desc_ocorrencias) VALUES ('81'	,'Extravio Parcial');
INSERT INTO TB_COD_OCORRENCIAS_TIVIT (cod,desc_ocorrencias) VALUES ('82'	,'Sobra de Mercadoria sem Nota Fiscal');
INSERT INTO TB_COD_OCORRENCIAS_TIVIT (cod,desc_ocorrencias) VALUES ('83'	,'Mercadoria em poder da SUFRAMA para Internação');
INSERT INTO TB_COD_OCORRENCIAS_TIVIT (cod,desc_ocorrencias) VALUES ('84'	,'Mercadoria Retirada para Conferência');
INSERT INTO TB_COD_OCORRENCIAS_TIVIT (cod,desc_ocorrencias) VALUES ('85'	,'Apreensão Fiscal da Mercadoria');
INSERT INTO TB_COD_OCORRENCIAS_TIVIT (cod,desc_ocorrencias) VALUES ('86'	,'Excesso de Carga/Peso');
INSERT INTO TB_COD_OCORRENCIAS_TIVIT (cod,desc_ocorrencias) VALUES ('87'	,'Férias Coletivas');
INSERT INTO TB_COD_OCORRENCIAS_TIVIT (cod,desc_ocorrencias) VALUES ('88'	,'Recusado, aguardando negociação');
INSERT INTO TB_COD_OCORRENCIAS_TIVIT (cod,desc_ocorrencias) VALUES ('89'	,'Aguardando refaturamento das mercadorias');
INSERT INTO TB_COD_OCORRENCIAS_TIVIT (cod,desc_ocorrencias) VALUES ('90'	,'Recusado pelo Redespachante');
INSERT INTO TB_COD_OCORRENCIAS_TIVIT (cod,desc_ocorrencias) VALUES ('91'	,'Entrega programada');
INSERT INTO TB_COD_OCORRENCIAS_TIVIT (cod,desc_ocorrencias) VALUES ('92'	,'Problemas Fiscais');
INSERT INTO TB_COD_OCORRENCIAS_TIVIT (cod,desc_ocorrencias) VALUES ('93'	,'Aguardando carta de correção');
INSERT INTO TB_COD_OCORRENCIAS_TIVIT (cod,desc_ocorrencias) VALUES ('94'	,'Recusa por divergência nas condições de pagamento');
INSERT INTO TB_COD_OCORRENCIAS_TIVIT (cod,desc_ocorrencias) VALUES ('95'	,'Carga aguardando vôo conexão                                                      -Cód. Transp. Aéreo');
INSERT INTO TB_COD_OCORRENCIAS_TIVIT (cod,desc_ocorrencias) VALUES ('96'	,'Carga sem embalagem própria para transp. Aéreo                           -Cód. Transp. Aéreo');
INSERT INTO TB_COD_OCORRENCIAS_TIVIT (cod,desc_ocorrencias) VALUES ('97'	,'Carga com dimensão superior ao porão da aeronave                        -Cód. Transp. Aéreo');
INSERT INTO TB_COD_OCORRENCIAS_TIVIT (cod,desc_ocorrencias) VALUES ('98'	,'Chegada na cidade ou filial de destino');
INSERT INTO TB_COD_OCORRENCIAS_TIVIT (cod,desc_ocorrencias) VALUES ('99'	,'Outros tipos de ocorrências não especificados acima');